name: GitHub action
on:
  push:
    branches: [main]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ci-example
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup LTS Version of Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test
