name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js Dependencies
        run: npm install
        # optional: you may want to cache the installed dependencies
        # to speed up the build process
        # see: https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#nodejs-example

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
